version: '3.8'
services:
  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: CapInvest
    volumes:
      - ./CapInvest:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=capinvest_dev
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: capinvest_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
